config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'categories#index'

  resources :line_items
  resources :carts

  resources :categories, only: [:show, :new, :create, :destroy] do
    resources :products, only: [:create]
  end
  resources :products, only: [:index, :show] do
    resources :reviews, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_cards.html.erb
<div class="product-card">
  <%= link_to product_path(product)  do %>
  <img src="<%= product.image %>" alt="">
  <h2><%= product.name %></h2>
  <div class="stars text-center">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
  </div>
  <div class="bottom-card text-center">
    <p><%= product.description %></p>
    <h3><%= humanized_money_with_symbol(product.price)  %>EUR</h3>
  </div>
    <p class="text-center">CLASSICS</p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar-shop.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-shop" id= "navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h2>douchbags</h2>
  <% end %>

  <div class="d-flex align-items-center d-sm-none">
     <div class="cart-item">
      <% if total_cart_items %>
      <%= link_to cart_path(@cart), class: "nav-link" do %>
      <span class="icon is-small">
        <i class="fas fa-shopping-bag"></i>
      </span>
      <span><%= cart_count_over_one %></span>
      <% end %>
      <% end %>
    </div>
    <button class="navbar-toggler d-sm-none" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Shop", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Stories", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", "#", class: "nav-link" %>
      </li>
      <li class="nav-item d-sm-none">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>


      <% else %>
      <li class="nav-item active">
        <%= link_to "Shop", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Stories", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", "#", class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="d-none d-sm-block guillo">
    <div class="cart-item">
      <% if total_cart_items %>
      <%= link_to cart_path(@cart), class: "nav-link" do %>
      <span class="icon is-small">
        <i class="fas fa-shopping-bag"></i>
      </span>
      <span><%= cart_count_over_one %></span>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-home" id= "navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h2>douchbags</h2>
  <% end %>

  <div class="d-flex align-items-center d-sm-none">
     <div class="cart-item">
      <% if total_cart_items %>
      <%= link_to cart_path(@cart), class: "nav-link" do %>
      <span class="icon is-small">
        <i class="fas fa-shopping-bag"></i>
      </span>
      <span><%= cart_count_over_one %></span>
      <% end %>
      <% end %>
    </div>
    <button class="navbar-toggler d-sm-none" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item ">
        <%= link_to "Shop", products_path, class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "Stories", "#", class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "About", "#", class: "nav-link" %>
      </li>
      <li class="nav-item  d-sm-none">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>


      <% else %>

      <li class="nav-item ">
        <%= link_to "Shop", products_path, class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "Stories", "#", class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "About", "#", class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="d-none d-sm-block guillo">
    <div class="cart-item">
      <% if total_cart_items %>
      <%= link_to cart_path(@cart), class: "nav-link" do %>
      <span class="icon is-small">
        <i class="fas fa-shopping-bag"></i>
      </span>
      <span><%= cart_count_over_one %></span>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_reviews.html.erb
<div class="review-container">
  <div class="count-review">
    <h1>Reviews</h1>
    <h4>Powered by <i class="fab fa-apple"></i></h4>
    <div class="review-count-star">
      <h2><%= @product.average %></h2>
      <h3><% @product.average.times do %>
        <i class="fas fa-star"></i>
        <% end %>
        <% (5 - @product.average).times do %>
        <i class="far fa-star"></i>
        <% end %></h3>
        <p><span id="review-count"><%=@product.reviews.size%></span> Reviews</p>
    </div>
    <h5><button id="myReviewButton" onClick="myReviewFunction();" ><i class="fas fa-edit"></i> Write a review</button></h5>
    <% if user_signed_in? %>
    <div style= "display:none;" id="reviewForm">
      <%= render 'reviews/form', product: @product, review: @review %>
      <% else %>
      <p>You must be <%= link_to "Login", new_user_session_path %> in to create a review for <%= @product.name %></p>
      <%end  %>
    </div>
    <br>
  </div>
    <div id="reviews">
      <% if @product.reviews.blank? %>
      <% else %>
      <% @product.reviews.reverse_each do |review| %>
      <%= render 'reviews/show', review: review %>
      <% end %>
      <% end %>
    </div>

    <script>
      function myReviewFunction() {
       var x = document.getElementById("reviewForm");
       x.style.display = "block";
     }
   </script>
</div>