config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'categories#index'

  resources :line_items
  resources :carts

  resources :categories, only: [:show, :new, :create, :destroy] do
    resources :products, only: [:create]
  end
  resources :products, only: [:index, :show] do
    resources :reviews, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="cart-container">
  <div class="keep-shopping">
    <h2><i class="fas fa-shopping-bag"></i> Shopping Cart (<%= @cart.line_items.count %>)</h2>
    <p><%= link_to 'X', root_path %></p>
  </div>
  <% if @cart.line_items.count >= 1 %>
  <div class="cart-items">
    <%= render(@cart.line_items) %>
  </div>
  <div class="price-top d-flex justify-content-between">
    <h3>Subtotal</h3>
    <p><span class="total-price"></span><%= number_to_currency(@cart.total_price) %></p>
  </div>
  <div class="price-top d-flex justify-content-between">
    <h3>Shipping</h3>
    <p>FREE</p>
  </div>
  <div class="delete-cart">
    <p><%= link_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button-delete" %></p>
  </div>
  <div class="price d-flex justify-content-between">
    <h3>Total</h3>
    <h2><span class="total-price"></span><%= number_to_currency(@cart.total_price) %></h2>
  </div>
  <div class="pl-3 pr-3">
    <button type="button" class="btn btn-primary btn-lg btn-block">PROCEED TO CHECKOUT</button>
  </div>
  <% else %>
   You have no items in your shopping cart.
  <% end %>
</div>